# **Indexación y Slicing**

In [1]:
import numpy as np

In [2]:
array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [3]:
print(array[1:4])

[20 30 40]


In [5]:
array = np.array([10,20,30,40,50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [8]:
index = [2,3,4]
print(array[index])

[30 40 50]


In [12]:
array = np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,1])

[[6 1 4]
 [4 7 2]
 [2 5 5]]
1


In [13]:
print(array[:2,:2])

[[6 1]
 [4 7]]
