# **Broadcasting**

In [2]:
import numpy as np

In [3]:
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [6]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[437 378 200]
 [224 326 481]
 [190 297 242]]
[[447 398 230]
 [234 346 511]
 [200 317 272]]


In [7]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0))

True


In [9]:
print(np.any(array > 0))

True


In [10]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)

[1 2 3 4 5 6]


In [12]:
stacked_v = np.vstack((array_a, array_b))
print(stacked_v)
stacked_h = np.hstack((array_a, array_b))
print(stacked_h)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [13]:
array_c = np.arange(1,10)
split_array = np.split(array_c,3)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
