In [1]:
import numpy as np

escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [2]:
vector = np.array([30,29,35,31,33,36,42])
print(vector)

[30 29 35 31 33 36 42]


In [4]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
tensor = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
diag = np.diag([1,2,3,4,5,6,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [10]:
random = np.random.random((2,3))
print(random)

[[0.37239937 0.03465583 0.35638864]
 [0.02402811 0.69134585 0.20674434]]
